on:
  push:
    branches: [bugfix-1095]
  pull_request:
    branches: [dev]
    types:
      - closed
  workflow_dispatch:

jobs:
  Build:
    environment: Development
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_DOMAIN }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Publish image to Azure Registry
        run: |
          docker build -t ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_REPO }}:${{ github.sha }} -t ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_REPO }}:${{ github.ref_name == 'main' && 'prod' || github.ref_name }}${{ github.ref_name != 'main' && '-latest' || 'latest' }} .
          docker push ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_REPO }} --all-tags
  Deploy:
    needs: Build
    environment:
      name: Development
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v2.0.0
        with:
          creds: ${{secrets.TDEI_CORE_AZURE_CREDS}}
      - name: Deploy to Dev Azure Container Instance
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.AZURE_RESOURCE_GROUP }}${{ github.run_number }}
          name: ${{ secrets.AZURE_CONTAINER_NAME }}
          image: ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_REPO }}:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_DOMAIN }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          ports: 80
          location: "west us"
          memory: 8
          environment-variables: |
            QUEUECONNECTION=${{ secrets.QUEUECONNECTION }}
            STORAGECONNECTION=${{ secrets.STORAGECONNECTION }}
            FORMATTER_SUBSCRIPTION=request-handler
            FORMATTER_TOPIC=osw-formatting-request
            FORMATTER_UPLOAD_TOPIC=osw-formatting-response
